# cmake/macos/buildspec.cmake
# macOS build setup:
#   1. Downloads obs-deps Qt 6.8.x (the SAME Qt OBS ships) into .deps/
#   2. Creates IMPORTED targets for OBS::libobs and OBS::obs-frontend-api
#      from /Applications/OBS.app
#   3. Downloads OBS 32.1.2 source for headers (obsconfig.h stub + libobs/*.h)
#   4. Downloads simde (required by OBS's sse-intrin.h on non-MSVC)
#
# After this file runs, find_package(Qt6) resolves to the obs-deps Qt 6.8.x,
# not Homebrew — eliminating the ABI mismatch that caused plugin load failures.

include_guard(GLOBAL)
include(buildspec_common)
include(FetchContent)

# ── Sanity check ──────────────────────────────────────────────────────────────
set(_obs_app "/Applications/OBS.app")
if(NOT EXISTS "${_obs_app}")
    message(FATAL_ERROR
        "OBS.app not found at /Applications/OBS.app\n"
        "Download OBS from https://obsproject.com/download and install it first.")
endif()
set(_obs_fw "${_obs_app}/Contents/Frameworks")

# ── Download Qt 6.8.x via obs-deps ───────────────────────────────────────────
# Uses the same package OBS itself was built against → exact ABI match.
function(_check_dependencies_plugin_macos)
    set(arch universal)
    set(platform macos-${arch})
    set(dependencies_dir "${CMAKE_CURRENT_SOURCE_DIR}/.deps")

    # Filename patterns from OBS's cmake/macos/buildspec.cmake
    set(qt6_filename    "macos-deps-qt6-VERSION-ARCH-REVISION.tar.xz")
    set(qt6_destination "obs-deps-qt6-VERSION-ARCH")

    # Download Qt only (we don't need the full prebuilt package for a plugin)
    set(dependencies_list qt6)
    _check_dependencies(${dependencies_list})

    # Remove macOS quarantine flag so the frameworks can be loaded
    if(EXISTS "${dependencies_dir}")
        execute_process(
            COMMAND xattr -r -d com.apple.quarantine "${dependencies_dir}"
            ERROR_QUIET RESULT_VARIABLE _xattr_result
        )
    endif()
endfunction()

_check_dependencies_plugin_macos()

# Explicitly point Qt6 at obs-deps so cmake never falls back to Homebrew.
# CMAKE_IGNORE_PREFIX_PATH alone is unreliable for all search paths on macOS.
file(GLOB _qt6_cmake_dirs
    LIST_DIRECTORIES TRUE
    "${CMAKE_CURRENT_SOURCE_DIR}/.deps/obs-deps-qt6-*/lib/cmake/Qt6"
)
if(_qt6_cmake_dirs)
    list(GET _qt6_cmake_dirs 0 _qt6_cmake_dir)
    set(Qt6_DIR "${_qt6_cmake_dir}" CACHE PATH "Qt6 from obs-deps" FORCE)
    message(STATUS "Qt6 → obs-deps: ${_qt6_cmake_dir}")
else()
    message(FATAL_ERROR "obs-deps Qt6 not found under .deps/ — re-run cmake to download it.")
endif()

# ── OBS source headers ────────────────────────────────────────────────────────
set(_obs_version "32.1.2")
set(_obs_deps_dir "${CMAKE_CURRENT_SOURCE_DIR}/.deps")
set(_obs_src_dir  "${_obs_deps_dir}/obs-studio-${_obs_version}")

if(NOT EXISTS "${_obs_src_dir}/libobs/obs-module.h")
    message(STATUS "Downloading OBS ${_obs_version} source (headers only)…")
    set(_obs_tarball "${_obs_deps_dir}/obs-studio-${_obs_version}.tar.gz")
    if(NOT EXISTS "${_obs_tarball}")
        file(DOWNLOAD
            "https://github.com/obsproject/obs-studio/archive/refs/tags/${_obs_version}.tar.gz"
            "${_obs_tarball}"
            STATUS _dl_status SHOW_PROGRESS
        )
        list(GET _dl_status 0 _dl_err)
        if(_dl_err GREATER 0)
            list(GET _dl_status 1 _dl_msg)
            file(REMOVE "${_obs_tarball}")
            message(FATAL_ERROR "Failed to download OBS source: ${_dl_msg}")
        endif()
    endif()
    file(ARCHIVE_EXTRACT INPUT "${_obs_tarball}" DESTINATION "${_obs_deps_dir}")
    message(STATUS "Downloading OBS ${_obs_version} source — done")
endif()

# simde (header-only; OBS's sse-intrin.h unconditionally includes it)
set(_simde_version "0.8.2")
set(_simde_dir "${_obs_deps_dir}/simde-${_simde_version}")
if(NOT EXISTS "${_simde_dir}/simde/x86/sse2.h")
    message(STATUS "Downloading simde v${_simde_version}…")
    set(_simde_tarball "${_obs_deps_dir}/simde-${_simde_version}.tar.gz")
    if(NOT EXISTS "${_simde_tarball}")
        file(DOWNLOAD
            "https://github.com/simd-everywhere/simde/archive/refs/tags/v${_simde_version}.tar.gz"
            "${_simde_tarball}"
            STATUS _dl_status SHOW_PROGRESS
        )
        list(GET _dl_status 0 _dl_err)
        if(_dl_err GREATER 0)
            list(GET _dl_status 1 _dl_msg)
            file(REMOVE "${_simde_tarball}")
            message(FATAL_ERROR "Failed to download simde: ${_dl_msg}")
        endif()
    endif()
    file(ARCHIVE_EXTRACT INPUT "${_simde_tarball}" DESTINATION "${_obs_deps_dir}")
    message(STATUS "Downloading simde v${_simde_version} — done")
endif()

# obsconfig.h stub (normally generated by OBS's own cmake run)
set(_obs_generated "${CMAKE_CURRENT_BINARY_DIR}/obs-generated")
file(MAKE_DIRECTORY "${_obs_generated}")
file(WRITE "${_obs_generated}/obsconfig.h"
    "/* minimal stub generated for plugin build */\n"
    "#pragma once\n"
    "#define OBS_DATA_PATH \"data\"\n"
    "#define OBS_PLUGIN_PATH \"obs-plugins\"\n"
    "#define OBS_PLUGIN_DESTINATION \"obs-plugins/64bit\"\n"
    "#define OBS_RELEASE_CANDIDATE 0\n"
    "#define OBS_BETA 0\n"
)

# ── OBS::libobs IMPORTED target ───────────────────────────────────────────────
add_library(OBS::libobs SHARED IMPORTED GLOBAL)
set_target_properties(OBS::libobs PROPERTIES
    IMPORTED_LOCATION "${_obs_fw}/libobs.framework/Versions/A/libobs"
    INTERFACE_INCLUDE_DIRECTORIES
        # simde first (provides <simde/x86/sse2.h>), then obsconfig, then libobs headers
        "${_simde_dir};${_obs_generated};${_obs_src_dir}/libobs"
)

# ── OBS::obs-frontend-api IMPORTED target ─────────────────────────────────────
add_library(OBS::obs-frontend-api SHARED IMPORTED GLOBAL)
set_target_properties(OBS::obs-frontend-api PROPERTIES
    IMPORTED_LOCATION "${_obs_fw}/obs-frontend-api.dylib"
    # OBS 30+ moved the header from UI/obs-frontend-api/ → frontend/api/
    INTERFACE_INCLUDE_DIRECTORIES "${_obs_src_dir}/frontend/api"
)

# ── RPATH for the plugin .so ──────────────────────────────────────────────────
# At runtime OBS resolves @rpath to OBS.app/Contents/Frameworks — that's where
# both libobs.framework and Qt*.framework live.
set(CMAKE_BUILD_RPATH  "${_obs_fw}")
set(CMAKE_INSTALL_RPATH "@loader_path/../../../../Frameworks")

message(STATUS "macOS build configured: Qt from obs-deps, OBS from ${_obs_app}")
