#!/usr/bin/env bash
# One-command launcher. Credentials are auto-generated by setup.sh and stored
# in relay.env. Edit relay.env to change the password or grace period.
cd "$(dirname "$0")"

if [[ -f relay.env ]]; then
  source relay.env
else
  echo "WARNING: relay.env not found — run setup.sh first to generate credentials." >&2
  # Emergency fallback so the panel at least refuses to start unprotected.
  export RELAY_PASSWORD='change-me'
  export RELAY_TOKEN='change-me'
  export RELAY_STOP_GRACE=20
fi

./start.sh
